### ISSUE TITLE
Python 3: Why teach sys.stdin.readline() over input()?

### ISSUE THREAD

**Issue by NeilCFord** [Charlotteis/noquestionistupid#21]
I am currently reading Python for Kids as part of a review process and in the chapter covering getting input from the user, the book exclusively uses sys.stdin.readline() to do this and doesn't mention input() at all.

My question is, is there a good technical reason for this or is it just a case of preference on behalf of the author?

**Comment by AMRoche** [comment]
At a guess, and from googling a bit / reading some docs, the following seems to sum it up quite well, and i'd agree with it;

>raw_input() takes an optional prompt argument. It also strips the trailing newline character from the >string it returns, and supports history features if the readline module is loaded.
>
>readline() takes an optional size argument, does not strip the trailing newline character and does not >support history whatsoever.
>
>Since they don't do the same thing, they're not really interchangeable. I personally prefer using >raw_input() to fetch user input, and readline() to read lines out of a file.

Taken from http://stackoverflow.com/questions/6966194/reading-a-line-from-standard-input-in-python

Also, from the python docs for version 3;

>Input()
>If the prompt argument is present, it is written to standard output without a trailing newline. The >function then reads a line from input, converts it to a string (stripping a trailing newline), and returns >that.

>readline()
>Read and return one line from the stream. If limit is specified, at most limit bytes will be read.

This seems to imply that readline reads the line (including new line character) from the stream, whereas input reads a line and returns a string.

To answer your question in a roundabout way, I think the reason the author uses readline() might be because streams are generally much more useful for files and I/O in general, whereas input() returns a string no matter what.

*NOTE* : I'm not a Python dev, i'm just a programmer who's googled some docs :)

**Comment by creature** [comment]
Another guess: do they handle reading files later? If so, I bet they use `readline()` as part of that. This gives the student one fewer thing to learn, and helps make mental connections by re-using & reinforcing earlier learning.

**Comment by NeilCFord** [comment]
Thanks both for your answers, very helpful.

The book does indeed go on to cover reading from files, so the reinforcing point is a good one.

At least there doesn't appear to be a glaring technical reason that I was unaware of, which is a relief.

**Comment by ImtiyazKhan117** [comment]
is there any common thing in raw_input and sys.stdin.readline() ?
